### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by gopinath6** [PaulSec/API-dnsdumpster.com#17]
OS :Win7
python 2.7 
python3

 i tried to call the api using both pythom version, getting below error.
Have  installed requirements also.

![image](https://user-images.githubusercontent.com/6551119/36627923-1d151c8e-1970-11e8-9b7b-4caaaa4ed067.png)

**Comment by PaulSec** [comment]
Mmmh.. interesting. 
I will investigate this and let you know what is happening. 

I can't reproduce with python 3.6:

```bash
✗ python3
Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dnsdumpster.DNSDumpsterAPI import DNSDumpsterAPI
>>> res = DNSDumpsterAPI(True).search('example.com')
[verbose] Retrieved token: aML8I9ctPNosWFRqgEFatv0KSeEhnxkR
>>> res
{'domain': 'example.com', 'dns_records': {'dns': [{'domain': 'b.iana-servers.net.', 'ip': '199.43.133.53', 'reverse_dns': 'b.iana-servers.net', 'as': 'AS1280', 'provider': 'Internet Systems Consortium, Inc.', 'country': 'United States', 'header': ''}, {'domain': 'a.iana-servers.net.', 'ip': '199.43.135.53', 'reverse_dns': 'a.iana-servers.net', 'as': 'AS26710', 'provider': 'ICANN', 'country': 'United States', 'header': ''}], 'mx': [], 'txt': ['"$Id: example.com 4415 2015-08-24 20:12:23Z davids $"', '"v=spf1 -all"'], 'host': [{'domain': 'www.example.com', 'ip': '93.184.216.34', 'reverse_dns': '', 'as': 'AS15133', 'provider': 'MCI Communications Services, Inc. d/b/a Verizon Business', 'country': 'United States', 'header': 'ECS (mdw/13C6)'}]}, 'image_data': b'iVBORw0KGgoAAAANSUhEUgAABi0AAAEVCAIAAAATkzH6AAAABmJLR0QA/wD/AP+gvaeTAAAgAElEQVR4nOzdd3hUZdo/8OeUqZmS3gsBQpX3RQJY2WUtIIo/BBHERR
```

**Comment by PaulSec** [comment]
Can you try to update BeautifulSoup by running ```pip install --upgrade beautifulsoup4``` ? 
This should fix the issue.

**Comment by gopinath6** [comment]
Its  working in python2, 
But the result is not proper

![image](https://user-images.githubusercontent.com/6551119/36679160-8dc7ba44-1b38-11e8-8d70-c66c604cce6d.png)

**Comment by PaulSec** [comment]
It's working as expected. 
What you get first is the image in the ```image_data``` entry. 

Check this file to interact with the different entries: https://github.com/PaulSec/API-dnsdumpster.com/blob/master/dnsdumpster/API_example.py
