### ISSUE TITLE
Messy output?

### ISSUE THREAD

**Issue by lushythedev** [PaulSec/API-dnsdumpster.com#26]
I am running a basic script that follows as:
```
from dnsdumpster.DNSDumpsterAPI import DNSDumpsterAPI

res = DNSDumpsterAPI({'verbose': False}).search('example.org')
print(res)
```

However, the output is extremely messy, and includes `imagedata` for some reason (which I have removed so it doesn't clog up this issue report)

> [verbose] Retrieved token: UMLo71IFn12zIWYb3uUWUHk1HM3qdWByvUOvuNinXXyfDkrhrwPjU12bvg2w0ftH
{'domain': 'example.org', 'dns_records': {'dns': [{'domain': 'a.iana-servers.net.', 'ip': '199.43.135.53', 'reverse_dns': 'a.iana-servers.net', 'as': 'ICANN-ANYCASTED-SERVICESUnited', 'provider': 'States', 'country': 'United States', 'header': ''}, {'domain': 'b.iana-servers.net.', 'ip': '199.43.133.53', 'reverse_dns': 'b.iana-servers.net', 'as': 'ICANN-ANYCASTED-SERVICESUnited', 'provider': 'States', 'country': 'United States', 'header': ''}], 'mx': [], 'txt': ['"v=spf1 -all"'], 'host': [{'domain': 'example.org', 'ip': '93.184.216.34', 'reverse_dns': '', 'as': 'EDGECASTUnited', 'provider': 'States', 'country': 'United States', 'header': 'ECS (sec/96DC)HTTPS: ECS (sec/9795)'}, {'domain': 'www.example.org', 'ip': '93.184.216.34', 'reverse_dns': '', 'as': 'EDGECASTUnited', 'provider': 'States', 'country': 'United States', 'header': 'ECS (sec/96DC)HTTPS: ECS (sec/9795)'}]}, 

How can I make the output pretty as shown in the repo?

**Comment by decidedlygray** [comment]
If you're talking about the example in the README, you can find the code here:

https://github.com/PaulSec/API-dnsdumpster.com/blob/master/dnsdumpster/API_example.py
