### ISSUE TITLE
get error when getting results

### ISSUE THREAD

**Issue by thangat02ptit** [PaulSec/API-dnsdumpster.com#33]
our monitor is showing this exception:
[verbose] Retrieved token: XuKapsQQceSllhKpDe8Q8UFxlJ62SLl1LGCKnnBUo7umkKUOLM61V4oYRXivBVto
There was an error getting results
[]
When I try the example in readme.md file.
I have installed all the necessary modules.
I have no idea why I got this error. Can you help me?

**Comment by Gertje823** [comment]
Got the same error. Using `pip install https://github.com/PaulSec/API-dnsdumpster.com/archive/master.zip --user` in stead of ` pip install dnsdumpster --user` fixed it.

**Comment by WiiZARDD** [comment]
> Got the same error. Using `pip install https://github.com/PaulSec/API-dnsdumpster.com/archive/master.zip --user` in stead of ` pip install dnsdumpster --user` fixed it.

Still doesn't work.

**Comment by PaulSec** [comment]
I updated the pip repository with the latest version, it should now work, thanks!
