### ISSUE TITLE
"There was an error getting results"

### ISSUE THREAD

**Issue by FormindMPO** [PaulSec/API-dnsdumpster.com#37]
The official pypi [dnsdumpster](https://pypi.org/project/dnsdumpster/) version doesn't work, it always break on `There was an error getting results`....

Thank to @Gertje823, you can install dnsdumpster from github like this : (see #33)

```shell
pip install https://github.com/PaulSec/API-dnsdumpster.com/archive/master.zip --user
```

____
### Explanation

I went deeper in the code and found out that @PaulSec changed lines 76 and 77 in **DNSDumpsterAPI.py**
            
```diff
- headers = {'Referer': dnsdumpster_url}
- data = {'csrfmiddlewaretoken': csrf_middleware, 'targetip': domain}

+ headers = {'Referer': dnsdumpster_url, 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36'}
+ data = {'csrfmiddlewaretoken': csrf_middleware, 'targetip': domain, 'user': 'free'}
```

If you add the `'user': 'free'` to the data field, it solves this issue

@PaulSec could you please push the https://github.com/PaulSec/API-dnsdumpster.com/archive/master.zip version to pypi ?
Thank you

**Comment by PaulSec** [comment]
@FormindMPO, @Gertje823, it's fixed. 
Let me know if it's OK for you - cheers !

**Comment by FormindMPO** [comment]
On rails !
