### ISSUE TITLE
had to use: from dnsdumpster.DNSDumpsterAPI import DNSDumpsterAPI

### ISSUE THREAD

**Issue by mkorthof** [PaulSec/API-dnsdumpster.com#9]

**Comment by PaulSec** [comment]
I see, did you clone the repository or did you use Pypi?

**Comment by mkorthof** [comment]
First I tried:
`$ pip3 install dnsdumpster --user`
then as root without --user
also tried "python3.4 -m pip install"

It installs to `/usr/local/lib/python3.4/dist-packages/dnsdumpster/{__init__.py,DNSDumpsterAPI.py}`
I'm on Debian 8 + python 3.

**Comment by PaulSec** [comment]
It's now all fixed. 👍 
Sorry for the late reply
